### ISSUE TITLE
CMake Error: create_project.tcl.in does not exist

### ISSUE THREAD

**Issue by masson2013** [fpgasystems/fpga-network-stack#13]
I was trying to do the make and it complained about the create_project.tcl:
**CMake Error: File /home/fpga-network-stack/projects/create_project.tcl.in does not exist.**
**CMake Error at CMakeLists.txt:97**
Line 97 of the CMakeLists.txt is looking for _projects_, I think it should be _scritps_ .

Thanks.

**Comment by dsidler** [comment]
Thanks for your feedback.
this is resolved with 6ddc53a6f5b2969f21927931edadfa41bce03ad0
