### ISSUE TITLE
Compilation fails at stage(make installip)

### ISSUE THREAD

**Issue by Oxygen-Chu** [fpgasystems/fpga-network-stack#14]
The "make installip" failed saying there's no valid part for the project.
CentOS 7 + Vivado 2019.2
~~~~~~~~~~~~~~~~~~~~~~~~~~~
Here's my procedure:
1. mkdir build (successful)
2. cd build (successful)
3. cmake .. -DDEVICE_NAME=vcu118 (successful)
4. make installip (failed)
~~~~~~~~~~~~~~~~~~~~~~~~~~~
And it errors out with message:
source /program/Xilinx/Vivado/2019.2/scripts/vivado_hls/hls.tcl -notrace
INFO: [HLS 200-10] Running '/program/Xilinx/Vivado/2019.2/bin/unwrapped/lnx64.o/vivado_hls'
INFO: [HLS 200-10] For user 'xlab' on host 'localhost' (Linux_x86_64 version 3.10.0-1062.4.3.el7.x86_64) on Tue Nov 26 03:56:57 CST 2019
INFO: [HLS 200-10] On os "CentOS Linux release 7.7.1908 (Core)"
INFO: [HLS 200-10] In directory '/home/xlab/Documents/toe/build/hls/ethernet_frame_padding'
Sourcing Tcl script 'make.tcl'
INFO: [HLS 200-10] Opening project '/home/xlab/Documents/toe/build/hls/ethernet_frame_padding/ethernet_frame_padding_prj'.
INFO: [HLS 200-10] Opening solution '/home/xlab/Documents/toe/build/hls/ethernet_frame_padding/ethernet_frame_padding_prj/solution1'.
INFO: [SYN 201-201] Setting up clock 'default' with a period of 3.2ns.
INFO: [HLS 200-10] Setting target device to 'xcvu9p-flga2104-2L-e'
INFO: [HLS 200-10] Adding design file '/home/xlab/Documents/toe/hls/ethernet_frame_padding/ethernet_frame_padding.cpp' to the project
INFO: [IMPL 213-8] Exporting RTL as a Vivado IP.

****** Vivado v2019.2 (64-bit)
  **** SW Build 2700185 on Thu Oct 24 18:45:48 MDT 2019
  **** IP Build 2699827 on Thu Oct 24 21:16:38 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

source run_ippack.tcl -notrace
ERROR: [Project 1-848] Could not get a valid part for the project. Make sure you have the required part installed, use the get_parts command to see the list of valid parts.
INFO: [Common 17-206] Exiting Vivado at Tue Nov 26 03:57:09 2019...
ERROR: [IMPL 213-28] Failed to generate IP.

**Comment by Oxygen-Chu** [comment]
Hi, Sidler~

I tried this build progress on Windows platform with Vivado 2019.2, it's alright.
It seems a bug on CentOS 7?

**Comment by dsidler** [comment]
This was tested on a modern linux distribution (Ubuntu 16.04 or 18.04, Arch linux). Cent Os uses old kernels.
Further, you should use vivado 2019.1

**Comment by Oxygen-Chu** [comment]
Solved, thank you :- )
