### ISSUE TITLE
Linux TCP stack not reacting to SYN packet sent from the FPGA board

### ISSUE THREAD

**Issue by lastweek** [fpgasystems/fpga-network-stack#26]
Hi all,

Has anyone tried to build a connection between the board and the Linux kernel TCP stack? 

I'm using the board as TCP client, and the Linux as TCP server. I found the Linux is not reacting to the first SYN packet from the board. The board and the server are connected directly with no switch in between.

I suppose I could debug the TCP headers whatnot, but just want to ask whether anyone has the same experience. Thanks.

Here is the SYN packet from tcpdump. The board is `192.168.1.8`. The server is `192.168.1.71`.
```
11:37:33.578934 IP (tos 0x0, ttl 64, id 0, offset 0, flags [none], proto TCP (6), length 48)
    192.168.1.8.32768 > 192.168.1.71.60000: Flags [S], cksum 0x32ff (correct), seq 1445134768, win 65535, options [mss 4096,wscale 2,eol], length 0
        0x0000:  0b0a 0908 0706 0605 0403 0201 0800 4500  ..............E.
        0x0010:  0030 0000 0000 4006 f728 c0a8 0108 c0a8  .0....@..(......
        0x0020:  0147 8000 ea60 5623 01b0 0000 0000 7002  .G...`V#......p.
        0x0030:  ffff 32ff 0000 0204 1000 0303 0200       ..2...........
```

**Comment by GraceDouX** [comment]
Hi, I want to do TCP iperf benchmarking, is the TCP port number 32768 in this project? Or where to see the TCP port number, if you have any suggestions, appreciated. 
I tested with TCP port number 32768, but it shows
`connect failed connection refused`
