### ISSUE TITLE
Upgrade to 100G TCP/IP

### ISSUE THREAD

**Issue by Oxygen-Chu** [fpgasystems/fpga-network-stack#8]
If possible, how about trying to upgrade the project to support 100G Ethernet MAC?
I can ask my friend to make two PCB with XCZU19EG (built-in 100G Ethernet MAC hard IP). and let's make it fun.
oxygen_chu@163.com
:- )

**Comment by mariodruiz** [comment]
Hi @Oxygen-Chu, we have been working in that for the last past year. You can check out Limago: https://github.com/hpcn-uam/Limago 
At the moment, only the VCU118 is supported.

**Comment by dsidler** [comment]
Hi @Oxygen-Chu,

I updated the code. The new code base supports a variable data path from 8bytes to 64bytes. This supports bandwidth of 10-100G.
Additionally to TCP, we now also support RoCEv2

Example projects for different boards can be found at https://github.com/fpgasystems/davos

**Comment by Oxygen-Chu** [comment]
WOW~
That's really a talented work, and thank you :- )
I'll have a try to play with this.
